### ISSUE TITLE
Cannot build?

### ISSUE THREAD

**Issue by koxu1996** [guigrpa/clocksy#1]
I execute following commands:
```
$ npm install --save clocksy
$ cd node_modules/clocksy
$ npm run build
```
and I'm getting error:
```
> clocksy@1.1.0 build /home/node-project/node_modules/clocksy
> npm run lint && npm run compile && npm run docs && npm run xxl


> clocksy@1.1.0 lint /home/node-project/node_modules/clocksy
> eslint src


> clocksy@1.1.0 compile /home/node-project/node_modules/clocksy
> node package && rm -rf ./lib ./libEs6 && babel -d lib src && cp -r src libEs6

src doesn't exist
```
Log: http://pastebin.com/8DmKP30Q

Am I doing something wrong or there is a bug?

**Comment by guigrpa** [comment]
I guess what you want is to use the module, not to build it. Usage instructions are in the `README.md` file, but please ask if something's not clear.

Otherwise, if you want to build the module, e.g. to contribute to it:

```sh
$ git clone http://github.com/guigrpa/clocksy
$ cd clocksy
$ npm install
$ npm run build
```

**Comment by koxu1996** [comment]
@guigrpa Yes, I want use it, but I am not sure how to do it. In example there is `import` statement, so I cannot simply run `nodejs server.js`, but I think I should compile it first. I also tried using babel-register, but it not work too. Could you tell me how to properly run server?

**Comment by koxu1996** [comment]
**Edit:**
I successfully ran server with installing _babel-register_ and creating entry point _index.js_:
```
require('babel-register')
require('./server_clocksy.js');  
```
Now I am wondering how to use client code in html file?

**Comment by guigrpa** [comment]
Glad you managed to do it!

For the client you'll need something like webpack or browserify in order to bundle a CommonJS module such as
Clocksy for use in your application.
